V8PLUS =	..

include $(V8PLUS)/Makefile.v8plus.defs

MODULE =	example

SRCS =	\
		example.c

ERRNO_JSON =	errno.json

PREFIX_NODE =	/opt/node
CC =		/opt/local/bin/gcc
CXX =		/opt/local/bin/g++

include $(V8PLUS)/Makefile.v8plus.targ
